services:
  frontend:
    build:
      context: ./frontend
    ports:
      - "3000:3000"

  backend:
    build:
      context: ./Backend
    ports:
      - "8080:8080"
    environment:
      - SPRING_DATASOURCE_URL=jdbc:mysql://db:3306/saboresdomundodb
      - SPRING_DATASOURCE_USERNAME=root
      - SPRING_DATASOURCE_PASSWORD=root

  db:
    image: mysql:8
    environment:
      MYSQL_DATABASE: saboresdomundodb
      MYSQL_ROOT_PASSWORD: root
    ports:
      - "3306:3306"